import { useState } from "react";
import { FilePlus2, LayoutGrid, LayoutTemplate, List, LoaderCircle, MoreHorizontal, Pencil, Plus, Search, Send, Trash2, Zap } from "lucide-react";
import type { Job, JobStatus, Project, PromptSnippet, Template } from "./appTypes";

const statusLabel: Record<JobStatus, string> = { queued: "等待执行", running: "生成中", succeeded: "已完成", failed: "生成失败", cancelled: "已中止" };
function formatDate(value: string): string {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "刚刚";
  return new Intl.DateTimeFormat("zh-CN", { month: "numeric", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(date);
}

export function ReplicaProjectCard({ project, job, palette, skillLabel, onOpen, onDelete }: { project: Project; job?: Job; palette: number; skillLabel?: string; onOpen: () => void; onDelete: () => void }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const status = job ? statusLabel[job.status] : "草稿";
  return <article className={`kppt-project-card kppt-palette-${palette}${menuOpen ? " is-menu-open" : ""}`}><button className="kppt-project-preview" type="button" onClick={onOpen}>{skillLabel && <em className="kppt-skill-badge">{skillLabel}</em>}<span>AI · DECK</span><div><strong>{project.title}</strong><small>{job?.template_name || "需求确认后可继续生成"}</small></div><i /><i /></button><div className="kppt-project-body"><button type="button" onClick={onOpen}>{project.title}</button><button className="kppt-card-menu" type="button" aria-label="项目更多操作" onClick={() => setMenuOpen((current) => !current)}><MoreHorizontal size={17} /></button>{menuOpen && <div className="kppt-card-menu-popover"><button type="button" onClick={onOpen}><Pencil size={14} />继续创作</button><button className="is-danger" type="button" onClick={onDelete}><Trash2 size={14} />删除项目</button></div>}</div><footer><span className={`kppt-status kppt-status-${job?.status ?? "draft"}`}>{status}</span><small>{formatDate(project.updated_at)}</small></footer></article>;
}

export function ProjectsPage(props: { projects: Project[]; jobsByProject: Record<string, Job[]>; query: string; setQuery: (value: string) => void; view: "grid" | "list"; setView: (value: "grid" | "list") => void; draft: string; setDraft: (value: string) => void; templates: Template[]; selectedTemplateId: string | null; setSelectedTemplateId: (value: string | null) => void; snippets: PromptSnippet[]; isSubmitting: boolean; notice: string; onCreate: () => void; onOpen: (project: Project) => void; onDelete: (project: Project) => void; onUseSnippet: (snippet: PromptSnippet) => void }) {
  const [showTemplates, setShowTemplates] = useState(false);
  const [showPrompts, setShowPrompts] = useState(false);
  const visible = props.projects.filter((project) => project.title.toLowerCase().includes(props.query.toLowerCase()));
  const selectedTemplate = props.templates.find((template) => template.id === props.selectedTemplateId);
  return <><section className="zc-hero"><div className="zc-eyebrow">AI 演示文稿创作</div><h1>把一个想法，变成一套能讲清楚的 PPT</h1><p>从需求到可编辑演示文稿，所有项目都在这里持续创作。</p><div className="zc-composer"><textarea value={props.draft} onChange={(event) => props.setDraft(event.target.value)} placeholder="例如：为人工智能行业发展准备一份 12 页的趋势分析 PPT，面向企业管理层" rows={5} /><div><div className="zc-composer-tools"><button className={showTemplates ? "is-active" : ""} type="button" onClick={() => setShowTemplates((current) => !current)}><LayoutTemplate size={16} />{selectedTemplate ? selectedTemplate.name : "选择模板"}</button><button className={showPrompts ? "is-active" : ""} type="button" onClick={() => setShowPrompts((current) => !current)}><Zap size={16} />引用提示词</button></div><button className="zc-send" type="button" aria-label="开始创作" disabled={!props.draft.trim() || props.isSubmitting} onClick={props.onCreate}>{props.isSubmitting ? <LoaderCircle className="zc-spin" size={18} /> : <Send size={18} />}</button></div>{showTemplates && <div className="zc-composer-popover"> <button className={!props.selectedTemplateId ? "is-selected" : ""} type="button" onClick={() => { props.setSelectedTemplateId(null); setShowTemplates(false); }}>自由创作</button>{props.templates.map((template) => <button className={props.selectedTemplateId === template.id ? "is-selected" : ""} type="button" key={template.id} onClick={() => { props.setSelectedTemplateId(template.id); setShowTemplates(false); }}>{template.name}<small>{template.page_count ?? 0} 页</small></button>)}</div>}{showPrompts && <div className="zc-composer-popover zc-prompt-popover">{props.snippets.length ? props.snippets.map((snippet) => <button type="button" key={snippet.id} onClick={() => { void props.onUseSnippet(snippet); setShowPrompts(false); }}><strong>{snippet.name}</strong><span>{snippet.content}</span></button>) : <p>还没有保存提示词</p>}</div>}</div></section><section className="zc-section"><header className="zc-section-head"><div><h2>最近项目</h2><p>继续上次的创作，生成过程和产物都会自动保存。</p></div><div className="zc-toolbar"><label><Search size={16} /><input value={props.query} onChange={(event) => props.setQuery(event.target.value)} placeholder="搜索项目" /></label><button className="zc-icon" type="button" aria-label="切换项目视图" onClick={() => props.setView(props.view === "grid" ? "list" : "grid")}>{props.view === "grid" ? <List size={17} /> : <LayoutGrid size={17} />}</button></div></header><div className={`zc-project-grid ${props.view === "list" ? "is-list" : ""}`}><button className="zc-new-project" type="button" onClick={() => document.querySelector<HTMLTextAreaElement>(".zc-composer textarea")?.focus()}><FilePlus2 size={25} /><strong>创建新 PPT</strong><span>从一句需求开始</span></button>{visible.map((project) => <ProjectCard key={project.id} project={project} job={props.jobsByProject[project.id]?.[0]} onOpen={() => props.onOpen(project)} onDelete={() => props.onDelete(project)} />)}</div></section></>;
}

function ProjectCard({ project, job, onOpen, onDelete }: { project: Project; job?: Job; onOpen: () => void; onDelete: () => void }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const status = job ? statusLabel[job.status] : "草稿";
  return <article className={`zc-project-card${menuOpen ? " is-menu-open" : ""}`}><button className="zc-project-cover" type="button" onClick={onOpen}><span>AI<br />PPT</span><strong>{project.title}</strong><i /></button><div className="zc-project-card-body"><div><button className="zc-project-title" type="button" onClick={onOpen}>{project.title}</button><small>{job?.template_name || "自由创作"} · 最近编辑 {formatDate(project.updated_at)}</small></div><button className="zc-icon zc-card-menu" type="button" aria-label="项目操作" onClick={() => setMenuOpen((current) => !current)}><MoreHorizontal size={18} /></button>{menuOpen && <div className="zc-action-menu"><button type="button" onClick={onOpen}><Pencil size={14} />继续创作</button><button className="is-danger" type="button" onClick={onDelete}><Trash2 size={14} />删除项目</button></div>}</div><footer><span className={`zc-status zc-status-${job?.status ?? "draft"}`}>{status}</span>{job?.template_name && <span>{job.template_name}</span>}</footer></article>;
}
